entrypoint: gunicorn -b :$PORT app:app
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: story-overlay-service-account.json
handlers:
  - static_dir: static
    url: /static
runtime: python37
service: story-overlay
